## Taking refrence from https://medium.com/analytics-vidhya/advanced-numpy-218584c60c63

In [1]:
import numpy as np

## Universal functions (ufuncs)

In [2]:
arr1 = np.random.randint(1,10 , 10)

In [3]:
arr2 = np.random.randint(1,10 , 10)

In [4]:
arr1

array([5, 3, 5, 5, 9, 3, 5, 2, 3, 6])

In [5]:
arr2

array([6, 3, 7, 2, 5, 6, 5, 3, 1, 1])

In [6]:
arr = np.add(arr1 , arr2)  #add function

In [7]:
arr

array([11,  6, 12,  7, 14,  9, 10,  5,  4,  7])

In [8]:
# other function are subtract , negative , multiply , divide , floor_divide , power , mod

In [9]:
np.log(19) # we can do the log as well

2.9444389791664403

In [10]:
arr1.min()

2

In [11]:
arr.max()

14

In [12]:
arr.sum()

85

In [13]:
arr = np.random.randint(30 , 90 , (4 , 8))

In [14]:
arr

array([[47, 62, 36, 41, 39, 38, 66, 84],
       [87, 72, 63, 55, 59, 49, 34, 49],
       [33, 79, 33, 59, 85, 71, 84, 58],
       [83, 73, 44, 38, 68, 68, 42, 65]])

In [15]:
#to calculate minimum of all in every row and column

In [16]:
arr.min(axis = 0)  #column wise

array([33, 62, 33, 38, 39, 38, 34, 49])

In [17]:
arr.min(axis = 1)  #row wise

array([36, 34, 33, 38])

In [18]:
# we must use universal function in numpy because normal min max function that povided by python is act differenty in 
# multidimentional array and we can use axis in numpy as well


## Broadcasting

In [19]:
# Broadcasting is nothing but a set of rules applied by NumPy to perform unfuncs on arrays of different sizes.

In [20]:
# rule says that the less size array must be streshed equal to larger one then do the operation

In [21]:
arr1 = np.arange(3)

In [22]:
arr2 = np.arange(3).reshape(3,1) # reshape changes the shape or array

In [23]:
arr1

array([0, 1, 2])

In [24]:
arr2

array([[0],
       [1],
       [2]])

In [25]:
arr3 = np.add(arr1,arr2) # in this they both streshed to the 3,3 size

In [26]:
arr1.shape #1,3

(3,)

In [27]:
arr2.shape

(3, 1)

In [28]:
arr3.shape   # they both streshed to the 3,3 size

(3, 3)

## Masking

In [29]:
# It allows us to extract, count, modify or manipulate values in an array based on certain criteria, 
# these criteria are specified using comparison operators and boolean operators.

In [30]:
arr = np.random.randint(10 , size= (3,4))

In [31]:
arr

array([[1, 7, 9, 4],
       [1, 2, 0, 8],
       [4, 5, 9, 6]])

In [32]:
# print all values where value is less then 5

In [33]:
[arr <5 ] #it give bool array

[array([[ True, False, False,  True],
        [ True,  True,  True, False],
        [ True, False, False, False]])]

In [34]:
arr[arr < 5]  # inner part of square bracker gives the array of boolean and if the value is true so outer 'arr' will print other wise false

array([1, 4, 1, 2, 0, 4])

In [35]:
# we can do the complex queries from that like we do in conditional statement

In [36]:
arr[(arr < 6 ) & ( arr > 3 )]

array([4, 4, 5])

In [37]:
# The keyword ‘and’ and ‘or’ performs single boolean operation on entire array while 
# bitwise ‘&’ and ‘|’ performs multiple boolean operations on elements of an array. 
# Always use bit-wise operators while masking.

## Fancy indexing

In [38]:
arr = np.random.randint(50 , size = 20)

In [39]:
arr

array([17,  5, 24, 38, 23, 27, 31,  6, 10, 39,  2,  9,  3, 13, 47, 11, 16,
       29, 21,  3])

In [40]:
print(arr[2] , arr[7])

24 6


In [41]:
#we can improve that 

In [42]:
arr[[2,7]]  # it takes array of indexes 

array([24,  6])

In [43]:
# for 2d array

In [44]:
arr = np.random.randint(30 , size = (10,5))

In [45]:
arr

array([[15, 12, 27,  1, 21],
       [17, 29, 14, 12,  3],
       [ 2,  7, 13,  4,  4],
       [14,  8,  8, 17, 22],
       [ 1, 23,  8, 28,  3],
       [ 3,  1, 23,  2, 29],
       [23, 23, 19, 23, 26],
       [14,  5,  7, 13, 12],
       [ 5, 18, 26,  8,  0],
       [ 0,  0, 24, 26,  9]])

In [46]:
row = [2,3,2,1]
col = [3,1,3,2]
arr[row , col]

array([ 4,  8,  4, 14])

In [47]:
arr[ 3, col]

array([17,  8, 17,  8])

## Sorting

In [48]:
# np.sort is a more efficient sorting function than Python’s built-in sort function. 
# Additionally, np.sort is aware of dimensions

In [49]:
arr = np.random.randint(30 , size = 20)

In [50]:
arr

array([15, 22, 11, 23, 15, 17,  9, 10,  2, 25, 22,  0, 15, 23, 12, 28,  2,
        6, 14, 22])

In [51]:
arr.sort()  # the sorting in numpy is in-place sorting means we lost the order of previous array

In [52]:
arr

array([ 0,  2,  2,  6,  9, 10, 11, 12, 14, 15, 15, 15, 17, 22, 22, 22, 23,
       23, 25, 28])

In [ ]:
arr = np.random.randint(30 , size = (10,10))