## Taking help from https://medium.com/analytics-vidhya/numpy-the-very-basics-6ce19206ee22

In [1]:
import numpy as np

In [2]:
numpy_array = np.array([[2,5,4],[2,5,6]] , dtype = int)    # multidimentional aray of datatype int 

In [3]:
numpy_array

array([[2, 5, 4],
       [2, 5, 6]])

In [4]:
numpy_array[1,2]  #getting the spesific data from an numpy array

6

## Different methods for creating array ex. zeros, ones, fill , arrange , linspace , random.randint , np.eye

In [5]:
arr = np.zeros((3,5) , dtype = int)  # this method create array of zeros by default datatype is float

In [6]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
arr = np.ones((3,5) , dtype = int) #this create array of 1

In [8]:
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
arr = np.empty([3, 3])

In [10]:
arr.fill(4)  #fill add value in every locaiton

In [11]:
arr

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [12]:
arr = np.arange(2,20 , 2) # arrange create array from starting index , final index , gap

In [13]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr = np.linspace(2,3,6) #it create arr of number evenly distributed 

In [29]:
arr

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [30]:
arr = np.random.randint(0,10,(3,4)) #create array of random number 

In [31]:
arr

array([[7, 1, 2, 1],
       [8, 2, 1, 4],
       [1, 4, 4, 3]])

In [37]:
arr = np.eye(3,3) # eye create idintity matrix

In [38]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Attributes of numpy

In [43]:
arr = np.random.randint(1,10, (3,4,5))

In [44]:
arr

array([[[2, 8, 2, 7, 2],
        [3, 9, 6, 8, 1],
        [1, 9, 9, 9, 4],
        [9, 1, 4, 2, 7]],

       [[3, 7, 7, 4, 6],
        [6, 7, 6, 2, 6],
        [7, 3, 5, 6, 2],
        [6, 3, 9, 7, 9]],

       [[2, 1, 5, 6, 5],
        [6, 6, 4, 8, 4],
        [5, 8, 7, 2, 8],
        [5, 9, 8, 7, 5]]])

In [52]:
arr.ndim #number of dimention

3

In [53]:
arr.shape #shape

(3, 4, 5)

In [56]:
arr.size #size

60

In [57]:
arr.dtype #datatype

dtype('int32')

In [58]:
arr.itemsize #Byte size of each array element.

4

In [60]:
arr.nbytes # total Byte size of array elements.

240

## Array indexing

In [66]:
arr = np.random.randint(1,5,(5,4))

In [67]:
arr

array([[4, 1, 1, 4],
       [4, 4, 2, 2],
       [2, 3, 2, 1],
       [4, 1, 3, 4],
       [4, 3, 2, 1]])

In [69]:
arr[2,3]

1

In [72]:
arr[-1,-2] #negative indexing start from end

2

## Array slicing

In [76]:
arr = np.arange(10)  # array_variable[start : stop: step]

In [77]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[2:5]

array([2, 3, 4])

In [82]:
arr[4: : -1]

array([4, 3, 2, 1, 0])

In [83]:
arr = np.random.randint(1,10,(4,5))

In [84]:
arr

array([[8, 3, 7, 3, 2],
       [6, 6, 3, 2, 6],
       [4, 3, 7, 6, 5],
       [9, 7, 9, 6, 1]])

In [85]:
arr[3:4:2,2:4:1]

array([[9, 6]])

## Concatinting and splitting

In [91]:
a= np.array([ 1,2,3,4 ])
b=np.array([5,6,7,8])
c=np.array([[9,8,7,6],[5,4,3,2]])
d=np.array([[5,6],[4,7]])

In [92]:
np.concatenate([a,b]) #it concat

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.vstack([a,c])  #vertically cocat

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [95]:
np.hstack([c,d])  # horizantally cocat

array([[9, 8, 7, 6, 5, 6],
       [5, 4, 3, 2, 4, 7]])

In [99]:
x1, x2, x3 = np.split(arr,[3,5]) # also there is hsplit and vsplit

In [100]:
x1,x2,x3

(array([[8, 3, 7, 3, 2],
        [6, 6, 3, 2, 6],
        [4, 3, 7, 6, 5]]),
 array([[9, 7, 9, 6, 1]]),
 array([], shape=(0, 5), dtype=int32))

In [101]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])